# Generated by Django 3.2.16 on 2022-10-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0002_rename_team_name_football_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='img',
            field=models.ImageField(default='hbbu', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
